### ISSUE TITLE
Firmware/Bootloader update Failed_1.8.1

### ISSUE THREAD

**Issue by xinai13994** [inertialsense/inertial-sense-sdk#27]
I have a INS Rugged unit used in work. The unit was working fine on 1.7.6 version. I tried to update the firmware to the newest (uINS 1.8.1) with the newly released Bootloader Version (SAMx70 v4b), the platform used to conduct upgrade is EvalTool 1.8.1.

However, the update failed on first attempt, then the serial connection not working ever since the failed attempt. Returned information in Firmware update window (Setting tab in EvalTool) is: "Starting bootloader...Unable to find bootloader...Attempting to reload bootloader...COM3: Firmware update ERROR!...Update failed to communicate"

Please advise.
![INS TS_06232020](https://user-images.githubusercontent.com/18513022/85592764-72cf2280-b614-11ea-9585-87f2967e8c16.JPG)

**Comment by siddirp** [comment]
Hi @xinai13994 Please just check the box to reopen the COM port and try again. Feel free to send an email to support@inertialsense.com if you need more assistance.

**Comment by natfallow** [comment]
Hi @xinai13994, I found that I had to first update the bootloader to v4b using the 1.7.6 version of evalTool - it seems version 1.8.1 cannot detect earlier bootloader versions. Your serial connection is likely no longer working because it is stuck in bootloader mode, which you should be able to resolve by restoring firmware version 1.7.6 (using evalTool 1.7.6).

**Comment by waltjohnson** [comment]
This issue is resolved in the latest bootloader.  Let us know if you have any further issues here.
